### ISSUE TITLE
Next Steps?

### ISSUE THREAD

**Issue by sditkovsky** [jbusecke/cmip6_omz#10]
From my understanding, we can say that the goal here is to get the **following workflows** running with a clean package of functions that don't reference `aguadv_omz_busecke_2021`,  `euc_dynamics`, or any other "downstream" repos:

-density binning woa and cmip6 data
-'de-drifting' cmip6 runs
-omz volume/trend analysis

I've started a notebook that goes through the steps of density binning the woa data and calculated the omz_thickness (`sam_tests/global_density_concept_observations`) to try out the different density ranges for each basin. This is based on the `preprocessing_density_transform.ipynb` on tigress.  Should the next step be getting that to run without any reference to other downstream repos? And add steps for binning cmip6 data?

Same idea for the `calculate_drift_files` notebook.

Let me know if you have something else in mind @jbusecke

**Comment by jbusecke** [comment]
> -density binning woa and cmip6 data
-'de-drifting' cmip6 runs
-omz volume/trend analysis

This seems right to me.

> I've started a notebook that goes through the steps of density binning the woa data and calculated the omz_thickness (sam_tests/global_density_concept_observations) to try out the different density ranges for each basin. This is based on the preprocessing_density_transform.ipynb on tigress. Should the next step be getting that to run without any reference to other downstream repos?

This is great. It should be the goal to eliminate the dependencies to `euc_dynamics` ,`agu_adv...`, and `busecke_et_al...`. Other dependencies to more general packages are fine IMO.

Calculating the drift corrections will basically be done with a very thin wrapper around https://github.com/jbusecke/cmip6_preprocessing/pull/126. I can take care of that, and start recomputing these values on the tigress system. But ultimately I want to produce these outputs in the cloud (this will take a bit more effort though, so I can test things on the Princeton system).

Ultimately it would be nice if these two steps can then serve as basis for both your study and I will also try to refactor my paper on top of this (if I can get it done before the review). 

> -omz volume/trend analysis

I think in terms of organization, we should produce the base data (yearly density transformed model output) here, but computing trends and the actual analysis (plots) should probably live in a paper specific repository? We can talk about this on a case by case basis. There might be some analysis steps that would benefit a larger audience. You can always import stuff from `busecke_et_al_...` for your study if you e.g. want to reproduce the plots.

Another important step in this workflow is the maintenance of the netcdf intake-esm catalog. I will dedicate a few hours to some maintenance and adding documentations to that package. Would you be willing to maintain that over at Princeton? It's pretty easy and I could ask David if we can set up an automated workflow. But in the long run I would like to pass the torch there. Are you using intake to read the data at all?

**Comment by sditkovsky** [comment]
> I think in terms of organization, we should produce the base data (yearly density transformed model output) here, but computing trends and the actual analysis (plots) should probably live in a paper specific repository? 

This  makes sense to me, too. Once I have the annual transformed model output, then things might get a little too 'exploratory' for this repo. 

> Another important step in this workflow is the maintenance of the netcdf intake-esm catalog. I will dedicate a few hours to some maintenance and adding documentations to that package. Would you be willing to maintain that over at Princeton? It's pretty easy and I could ask David if we can set up an automated workflow. But in the long run I would like to pass the torch there. Are you using intake to read the data at all?

I have been using it to read in the model data and I think it's a great tool. So I could probably do this, but the torch might not be fully passed until after generals haha...

**Comment by jbusecke** [comment]
> I have been using it to read in the model data and I think it's a great tool. So I could probably do this, but the torch might not be fully passed until after generals haha...

I am sorry if this sounded like I was trying to pressure you with this. If at any time you could help with this, I would greatly appreciate it, but obviously that should not interfere with your academic work!

**Comment by jbusecke** [comment]
I think most of this is also covered in #18. Ill close this.
