### ISSUE TITLE
xgcm_transform_wrapper

### ISSUE THREAD

**Issue by sditkovsky** [jbusecke/cmip6_omz#13]
@jbusecke Are you working on bringing the [xgcm_transform_wrapper](https://github.com/jbusecke/aguadv_omz_busecke_2021/blob/main/aguadv_omz_busecke_2021/vertical_transformation.py) function into xgcm, or should that come here?

**Comment by jbusecke** [comment]
I havent started that yet, but will soon. Discussion can be found over [here](https://github.com/xgcm/xgcm/issues/340)

I think you could use the old code for testing, but would want to use upstream capabilites for production (publication). 

My suggestion is to bring the wrapper into the 'upstream' module and add a warning that will be triggered each time that old code runs?

**Comment by jbusecke** [comment]
Closing in favor of #18
