### ISSUE TITLE
Detrending Demo functions to upstream

### ISSUE THREAD

**Issue by sditkovsky** [jbusecke/cmip6_omz#15]
I'm going through the Detrending Demo notebook and running into some bugs within the aguadv_... functions (`load_single_datasets()`, etc). I'm going to bring them over to `cmip6_omz.upstream_stash` for now to debug, unless you're about to bring them somewhere else @jbusecke. It looks like the first round will be

- `load_single_datasets`
- `_pick_latest_version`
- `non_aggregated_ds_dict_key_processor`
- ` _loading_preprocessing`

(The immediate issue I'm running into is with the chunking logic in ` _loading_preprocessing`: `ds.x` is called, but there is no variable `x`)

Should I make `non_aggregated_ds_dict_key_processor` suitable for .nc (right now only works for .zarr?)? Were .zarr files necessary to solve the storage/memory issues, or it is okay to maintain a workflow for netcdf files?

**Comment by jbusecke** [comment]
Tasks from our zoom call:

- [ ] Implement [`fix_metadata_issues`](https://github.com/jbusecke/euc_dynamics/blob/ee0d786769a6ba223ebbb8c423375eb4417de41a/euc_dynamics/cmip6_preprocessing_stash.py#L514) in cmip6_pp
- [ ] Redo the NetCDF catalog on the Princeton systems (check for duplicates).

With these changes the above should not be needed anymore.

**Comment by jbusecke** [comment]
Is everything here covered in #18 ? Then I would favor closing this just to stay organized.
