### ISSUE TITLE
We need to get rid of these dependencies

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/cmip6_omz#23]
https://github.com/jbusecke/cmip6_omz/blob/57c515342d85715d0368948d7ddbbee8736504bb/cmip6_omz/utils.py#L21-L28

I just got an error when I tried to use #22 due to the fact that we are still importing from `aguadv_...` here. @sditkovsky are you using these at all? Otherwise I would opt to remove them.

**Comment by sditkovsky** [comment]
Everything in that file is phased out at this point. Should be safe to take it out.

**Comment by jbusecke** [comment]
Ok Ill do that over in #22
