### ISSUE TITLE
Migrate reconstruct_areacello() out of cmip6_omz.datasets

### ISSUE THREAD

**Issue by sditkovsky** [jbusecke/cmip6_omz#9]
Also needs a test. What should we name the new module and what other sorts of functions should belong there? Grid metrics functions?

**Comment by jbusecke** [comment]
Good question. I think that this functionality will soon be migrated somewhere else (and there might be some other ones too). I could think of 'upstream.py' or 'upstream_stash.py'. This could hold anything that eventually moves into other packages upstream (cmip6_pp, xgcm, xarray, ...).

**Comment by jbusecke** [comment]
I think this is solved? We left the 'copy paste' version in the `datasets.py` module just for the WOA data, right?
